import type { CloudSnapshotV1, DomainMatch, DomainPayment, DomainSessionPlayer, MatchHistory, MatchPlayer, ScoreSettings } from "@shuttle-queue/domain";
import { applyPlayerDeletion, previewPlayerDeletion, rebuildSnapshotCareerStats, suggestMatch, validateScores, historyDurationSeconds } from "@shuttle-queue/domain";
import type { Court, FeePlayer, FeeSummary, HistoryMatch, HistoryResponse, Match, Payment, Player, PlayerHistoryResponse, QueueState, Ranking, SessionPlayer, SessionSummary, Suggestion } from "../api";
import { request } from "../api";
import { appendAudit, clearAccountData, firstProfile, getDeviceId, getMeta, hasSnapshot, listPendingAudits, offlineDb, readSnapshot, replaceSnapshot, saveProfile, storageEstimate, updateLocalSnapshot } from "./db";

const id = () => crypto.randomUUID();
const now = () => new Date().toISOString();
const parseBody = (init?: RequestInit) => { try { return init?.body ? JSON.parse(String(init.body)) as Record<string, unknown> : {}; } catch { return {}; } };
const pathParts = (path: string) => (path.split("?")[0] ?? path).split("/").filter(Boolean);
const query = (path: string) => new URLSearchParams(path.split("?")[1] ?? "");
const prettyDate = (value?: string | null) => value ? new Date(value).toISOString() : null;
const skillWeights: Record<string, number> = { NEWBIE: 1, BEGINNER: 2, INTERMEDIATE: 3, UPPER_INTERMEDIATE: 4, ADVANCED: 5 };

export async function hasLocalSnapshot() { return hasSnapshot(); }
export async function retainedProfile() { return firstProfile(); }
async function currentAccountId() { let preferred: string | null = null; try { preferred = window.localStorage.getItem("shuttle-queue-current-account"); } catch { /* ignore storage access failures */ } if (preferred && await hasSnapshot(preferred)) return preferred; const row = (await offlineDb.snapshots.toArray())[0]; if (!row) throw new Error("Download this account before working offline."); return row.accountId; }

function requireSnapshot(snapshot: CloudSnapshotV1, sessionId?: string) {
  const session = sessionId ? snapshot.sessions.find((item) => item.id === sessionId) : undefined;
  if (sessionId && !session) throw new Error("Session not found.");
  return session;
}

const toSessionSummary = (snapshot: CloudSnapshotV1, session: CloudSnapshotV1["sessions"][number]): SessionSummary => ({ id: session.id, name: session.name, sessionDate: session.sessionDate, status: session.status, startedAt: session.startedAt ?? null, endedAt: session.endedAt ?? null, version: session.version, playerCount: snapshot.sessionPlayers.filter((item) => item.sessionId === session.id).length, courtCount: snapshot.courts.filter((item) => item.sessionId === session.id).length, scoring: { pointsToWin: session.pointsToWin, winBy: session.winBy, scoreCap: session.scoreCap, bestOf: session.bestOf } });
const toSessionPlayer = (player: DomainSessionPlayer): SessionPlayer => ({ id: player.id, playerId: player.playerId, displayName: player.displayName, gender: player.gender, skillLevel: player.skillLevel, skillWeight: player.skillWeight, status: player.status, matchesPlayed: player.matchesPlayed, wins: player.wins, losses: player.losses, ...(player.pointsFor !== undefined ? { pointsFor: player.pointsFor } : {}), ...(player.pointsAgainst !== undefined ? { pointsAgainst: player.pointsAgainst } : {}), ...(player.amountDueMinor !== undefined ? { amountDueMinor: player.amountDueMinor } : {}), ...(player.manualPriority !== undefined ? { manualPriority: player.manualPriority } : {}), currentMatchId: player.currentMatchId ?? null, ...(player.queueEnteredAt ? { queueEnteredAt: player.queueEnteredAt } : {}) });
const toPayment = (payment: DomainPayment): Payment => ({ id: payment.id, sessionId: payment.sessionId, sessionPlayerId: payment.sessionPlayerId, kind: payment.kind as Payment["kind"], method: payment.method === "CASH" || payment.method === "EWALLET" || payment.method === "OTHER" ? payment.method : null, amountMinor: payment.amountMinor, reference: payment.reference ?? null, note: payment.note ?? null, occurredAt: payment.occurredAt, createdAt: payment.createdAt });
function allocateEqualSplit(total: number, playerIds: string[]) { const base = playerIds.length ? Math.floor(total / playerIds.length) : 0; const remainder = playerIds.length ? total - base * playerIds.length : 0; return new Map(playerIds.map((playerId, index) => [playerId, base + (index < remainder ? 1 : 0)])); }
function feeSummary(snapshot: CloudSnapshotV1, sessionId: string): FeeSummary {
  const config = snapshot.feeConfigs.find((item) => item.sessionId === sessionId);
  const payments = snapshot.payments.filter((item) => item.sessionId === sessionId);
  const balances = new Map<string, { collected: number; refunded: number; waived: number }>();
  for (const payment of payments) {
    const balance = balances.get(payment.sessionPlayerId) ?? { collected: 0, refunded: 0, waived: 0 };
    if (payment.kind === "COLLECTION") balance.collected += payment.amountMinor;
    if (payment.kind === "REFUND") balance.refunded += payment.amountMinor;
    if (payment.kind === "WAIVER") balance.waived += payment.amountMinor;
    if (payment.kind === "WAIVER_REVERSAL") balance.waived -= payment.amountMinor;
    balances.set(payment.sessionPlayerId, balance);
  }
  const players: FeePlayer[] = snapshot.sessionPlayers.filter((item) => item.sessionId === sessionId).map((player) => {
    const balance = balances.get(player.id) ?? { collected: 0, refunded: 0, waived: 0 };
    const collectedMinor = balance.collected - balance.refunded;
    const outstandingMinor = Math.max(0, (player.amountDueMinor ?? 0) - collectedMinor - balance.waived);
    const status: FeePlayer["status"] = balance.waived >= (player.amountDueMinor ?? 0) && (player.amountDueMinor ?? 0) > 0 ? "WAIVED" : outstandingMinor === 0 && (player.amountDueMinor ?? 0) > 0 ? "PAID" : collectedMinor > 0 ? "PARTIAL" : "UNPAID";
    return { sessionPlayerId: player.id, displayName: player.displayName, dueMinor: player.amountDueMinor ?? 0, collectedMinor, waivedMinor: balance.waived, outstandingMinor, status };
  });
  const expectedMinor = config?.mode === "EQUAL_SPLIT" ? config.expectedSessionCostMinor ?? 0 : players.reduce((sum, player) => sum + player.dueMinor, 0);
  return { config: (config as FeeSummary["config"]) ?? null, expectedMinor, collectedMinor: players.reduce((sum, player) => sum + player.collectedMinor, 0), outstandingMinor: players.reduce((sum, player) => sum + player.outstandingMinor, 0), paymentCount: payments.length, players };
}
const toCourt = (court: CloudSnapshotV1["courts"][number]): Court => ({ id: court.id, name: court.name, status: court.status, displayOrder: court.displayOrder, currentMatchId: court.currentMatchId ?? null });
const findPlayer = (snapshot: CloudSnapshotV1, idValue: string) => snapshot.sessionPlayers.find((item) => item.id === idValue);
const findCourt = (snapshot: CloudSnapshotV1, idValue?: string) => snapshot.courts.find((item) => item.id === idValue);

function toMatch(snapshot: CloudSnapshotV1, value: DomainMatch): Match {
  return { id: value.id, sessionId: value.sessionId, status: value.status, courtId: value.courtId ?? null, startedAt: value.startedAt ?? null, completedAt: value.completedAt ?? null, queuedAt: value.queuedAt, winnerTeam: value.winnerTeam ?? null, cancellationReason: value.cancellationReason ?? null, participants: value.participants.map((participant) => ({ id: participant.id, sessionPlayerId: participant.sessionPlayerId, team: participant.team, teamSlot: participant.teamSlot, displayName: findPlayer(snapshot, participant.sessionPlayerId)?.displayName ?? "Unknown player" })) };
}

function scoreFor(match: DomainMatch) {
  const revision = match.scoreRevisions.find((item) => item.id === match.currentRevisionId) ?? [...match.scoreRevisions].sort((a, b) => b.revisionNumber - a.revisionNumber)[0];
  return revision;
}

function toHistoryMatch(snapshot: CloudSnapshotV1, match: DomainMatch): HistoryMatch {
  const revision = scoreFor(match);
  const court = findCourt(snapshot, match.courtId ?? undefined);
  return { id: match.id, sessionId: match.sessionId, source: match.source, matchmakingMode: match.matchmakingMode ?? null, format: match.participants.length === 2 ? "SINGLES" : "DOUBLES", court: court ? { id: court.id, name: court.name } : null, startedAt: match.startedAt ?? null, completedAt: match.completedAt ?? null, durationSeconds: match.startedAt && match.completedAt ? historyDurationSeconds(match.startedAt, match.completedAt) : null, winnerTeam: match.winnerTeam ?? revision?.winnerTeam ?? null, score: revision ? { revisionNumber: revision.revisionNumber, winnerTeam: revision.winnerTeam, games: revision.games.map((game) => ({ gameNumber: game.gameNumber, teamAScore: game.teamAScore, teamBScore: game.teamBScore, winnerTeam: game.winnerTeam })) } : null, participants: match.participants.map((participant) => { const player = findPlayer(snapshot, participant.sessionPlayerId); const global = snapshot.players.find((item) => item.id === player?.playerId); return { sessionPlayerId: participant.sessionPlayerId, playerId: player?.playerId ?? "", displayName: player?.displayName ?? "Unknown player", gender: player?.gender ?? global?.gender ?? "MALE", skillLevel: player?.skillLevel ?? global?.skillLevel ?? "NEWBIE", team: participant.team, teamSlot: participant.teamSlot }; }) };
}

function historyFor(snapshot: CloudSnapshotV1, sessionId: string, search = "") {
  const normalized = search.trim().toLowerCase();
  return snapshot.matches.filter((match) => match.sessionId === sessionId && match.status === "COMPLETED").filter((match) => !normalized || match.participants.some((participant) => findPlayer(snapshot, participant.sessionPlayerId)?.displayName.toLowerCase().includes(normalized))).sort((a, b) => (b.completedAt ?? "").localeCompare(a.completedAt ?? ""));
}

function paginate<T>(items: T[], page: number, pageSize: number) {
  const total = items.length; const totalPages = Math.max(1, Math.ceil(total / pageSize)); const safePage = Math.min(Math.max(1, page), totalPages);
  return { items: items.slice((safePage - 1) * pageSize, safePage * pageSize), pagination: { page: safePage, pageSize, total, totalPages } };
}

function historyMaps(snapshot: CloudSnapshotV1, sessionId: string): MatchHistory {
  const partners = new Map<string, Map<string, number>>(); const opponents = new Map<string, Map<string, number>>(); const quartets = new Map<string, number>();
  const add = (map: Map<string, Map<string, number>>, a: string, b: string) => { if (!map.has(a)) map.set(a, new Map()); map.get(a)!.set(b, (map.get(a)!.get(b) ?? 0) + 1); };
  for (const match of snapshot.matches.filter((item) => item.sessionId === sessionId && item.status === "COMPLETED")) { const sorted = match.participants.map((item) => item.sessionPlayerId).sort(); quartets.set(sorted.join(":"), (quartets.get(sorted.join(":")) ?? 0) + 1); const teamA = match.participants.filter((item) => item.team === "A"); const teamB = match.participants.filter((item) => item.team === "B"); for (const team of [teamA, teamB]) if (team.length === 2) { add(partners, team[0]!.sessionPlayerId, team[1]!.sessionPlayerId); add(partners, team[1]!.sessionPlayerId, team[0]!.sessionPlayerId); } for (const a of teamA) for (const b of teamB) { add(opponents, a.sessionPlayerId, b.sessionPlayerId); add(opponents, b.sessionPlayerId, a.sessionPlayerId); } }
  return { partners, opponents, quartets };
}

function sessionSettings(session: CloudSnapshotV1["sessions"][number]): ScoreSettings { return { pointsToWin: session.pointsToWin, winBy: session.winBy, scoreCap: session.scoreCap, bestOf: session.bestOf }; }

function ensureWaiting(snapshot: CloudSnapshotV1, sessionId: string, ids: string[]) {
  const players = ids.map((playerId) => findPlayer(snapshot, playerId));
  if (players.some((player) => !player || player.sessionId !== sessionId || player.status !== "WAITING" || player.currentMatchId)) throw new Error("One or more selected players are no longer waiting.");
  return players as DomainSessionPlayer[];
}

function addLocalAudit(snapshot: CloudSnapshotV1, sessionId: string, action: string, entityId: string) {
  const event = { id: id(), sessionId: sessionId || null, action, entityType: "OFFLINE_OPERATION", entityId, reason: "Recorded offline", requestId: `offline:${id()}`, createdAt: now() };
  snapshot.audits.push(event);
  return event;
}

async function mutate(accountId: string, sessionId: string, action: string, updater: (snapshot: CloudSnapshotV1) => unknown) {
  let event: ReturnType<typeof addLocalAudit> | undefined;
  const result = await updateLocalSnapshot(accountId, async (snapshot) => { const value = await updater(snapshot); event = addLocalAudit(snapshot, sessionId, action, sessionId || accountId); return value; });
  if (event) await appendAudit(accountId, { sessionId: event.sessionId, action: event.action, entityType: event.entityType, entityId: event.entityId, reason: event.reason });
  return result;
}

export async function sessions(accountId: string) { const snapshot = await readSnapshot(accountId); return snapshot ? snapshot.sessions.map((session) => toSessionSummary(snapshot, session)).sort((a, b) => b.sessionDate.localeCompare(a.sessionDate)) : []; }
export async function players(accountId: string) { const snapshot = await readSnapshot(accountId); return (snapshot?.players ?? []).filter((player) => player.status === "ACTIVE") as Player[]; }

export async function handleRequest(accountId: string, path: string, init?: RequestInit): Promise<unknown> {
  if (accountId === "current") accountId = await currentAccountId();
  const parts = pathParts(path); const method = (init?.method ?? "GET").toUpperCase(); const body = parseBody(init); const sessionId = parts[1]; const snapshot = await readSnapshot(accountId); if (!snapshot) throw new Error("Download this account before working offline.");
  if (parts[0] === "sessions" && parts.length === 1 && method === "GET") return sessions(accountId);
  if (parts[0] === "players" && parts.length === 1 && method === "GET") return players(accountId);
  if (parts[0] === "players" && parts[1] === "deletion-preview" && method === "POST") { const ids = (body.playerIds as string[] | undefined) ?? []; if (!ids.length || ids.length > 100 || new Set(ids).size !== ids.length || ids.some((idValue) => !snapshot.players.some((player) => player.id === idValue))) throw new Error("Select between one and 100 unique players you own."); return previewPlayerDeletion(snapshot, ids); }
  if (parts[0] === "players" && parts[1] === "delete" && method === "POST") return deletePlayers(accountId, (body.playerIds as string[] | undefined) ?? []);
  if (parts[0] === "players" && parts.length === 1 && method === "POST") return createPlayer(accountId, body);
  if (parts[0] === "sessions" && parts.length === 1 && method === "POST") return createSession(accountId, body);
  if (parts[0] === "sessions" && parts[2] === "players" && parts.length === 3 && method === "GET") return listSessionPlayers(snapshot, sessionId!);
  if (parts[0] === "sessions" && parts[2] === "players" && parts.length === 3 && method === "POST") return addPlayers(accountId, sessionId!, body);
  if (parts[0] === "sessions" && parts[2] === "queue" && method === "GET") return getQueue(snapshot, sessionId!);
  if (parts[0] === "sessions" && parts[2] === "courts" && parts.length === 3 && method === "GET") return (snapshot.courts.filter((court) => court.sessionId === sessionId).sort((a, b) => a.displayOrder - b.displayOrder).map(toCourt));
  if (parts[0] === "sessions" && parts[2] === "courts" && parts.length === 3 && method === "POST") return createCourt(accountId, sessionId!, body);
  if (parts[0] === "sessions" && parts[2] === "courts" && parts.length === 5 && method === "PATCH") return updateCourt(accountId, sessionId!, parts[3]!, body);
  if (parts[0] === "sessions" && parts[2] === "fees" && parts.length === 3 && method === "GET") return feeSummary(snapshot, sessionId!);
  if (parts[0] === "sessions" && parts[2] === "fees" && parts[3] === "config" && method === "PUT") return updateFeeConfig(accountId, sessionId!, body);
  if (parts[0] === "sessions" && parts[2] === "payments" && parts.length === 3 && method === "GET") return snapshot.payments.filter((payment) => payment.sessionId === sessionId).sort((a, b) => b.occurredAt.localeCompare(a.occurredAt)).map(toPayment);
  if (parts[0] === "sessions" && parts[2] === "payments" && parts.length === 3 && method === "POST") return createPayment(accountId, sessionId!, body);
  if (parts[0] === "sessions" && parts[2] === "players" && parts.length === 5 && method === "POST") return transitionPlayer(accountId, sessionId!, parts[3]!, parts[4]!);
  if (parts[0] === "sessions" && parts[2] === "suggestions" && method === "POST") return getSuggestion(snapshot, sessionId!, body);
  if (parts[0] === "sessions" && parts[2] === "matches" && method === "POST") return createMatch(accountId, sessionId!, body);
  if (parts[0] === "sessions" && parts[2] === "matches" && method === "GET") return snapshot.matches.filter((match) => match.sessionId === sessionId).sort((a, b) => b.queuedAt.localeCompare(a.queuedAt)).map((match) => toMatch(snapshot, match));
  if (parts[0] === "sessions" && parts[2] === "history" && method === "GET") return getHistory(snapshot, sessionId!, path);
  if (parts[0] === "sessions" && parts[2] === "players" && parts[4] === "history" && method === "GET") return getPlayerHistory(snapshot, sessionId!, parts[3]!, path);
  if (parts[0] === "sessions" && parts[2] === "rankings" && method === "GET") return getRankings(snapshot, sessionId!);
  if (parts[0] === "sessions" && parts[2] === "start" && method === "POST") return startSession(accountId, sessionId!);
  if (parts[0] === "sessions" && parts[2] === "reset" && method === "POST") return resetSession(accountId, sessionId!);
  if (parts[0] === "sessions" && parts.length === 2 && method === "DELETE") { await deleteSession(accountId, sessionId!, body.playerDisposition === "DELETE_ALL" ? "DELETE_ALL" : "KEEP"); return undefined; }
  if (parts[0] === "matches" && parts[2] === "start" && method === "POST") return startMatch(accountId, parts[1]!, String(body.courtId ?? ""));
  if (parts[0] === "matches" && parts[2] === "complete" && method === "POST") return completeMatch(accountId, parts[1]!, body.games as Array<{ teamAScore: number; teamBScore: number }>);
  if (parts[0] === "matches" && parts[2] === "cancel" && method === "POST") return cancelMatch(accountId, parts[1]!);
  if (parts[0] === "rankings" && parts[1] === "career" && method === "GET") return [];
  throw new Error("This operation is not available offline yet.");
}

async function createPlayer(accountId: string, body: Record<string, unknown>) { return updateLocalSnapshot(accountId, (snapshot) => { const displayName = String(body.displayName ?? "").trim(); if (!displayName) throw new Error("Display name is required."); if (snapshot.players.some((player) => player.displayName.toLowerCase() === displayName.toLowerCase())) throw new Error("A player with that name already exists."); const skillLevel = String(body.skillLevel ?? "NEWBIE") as any; const player = { id: id(), displayName, gender: body.gender as "MALE" | "FEMALE", skillLevel, skillWeight: Number(body.skillWeight ?? skillWeights[skillLevel] ?? 1), status: "ACTIVE" }; snapshot.players.push(player); return player; }); }
async function createSession(accountId: string, body: Record<string, unknown>) { return updateLocalSnapshot(accountId, (snapshot) => { const name = String(body.name ?? "").trim(); if (!name) throw new Error("Session name is required."); const session = { id: id(), name, normalizedName: name.toLowerCase(), sessionDate: String(body.sessionDate ?? now()), status: "DRAFT" as const, startedAt: null, endedAt: null, cancelledAt: null, pointsToWin: 31, winBy: 1, scoreCap: 31, bestOf: 1 as const, minimumRestMinutes: 0, matchmakingAlgorithm: "v2-rotation", matchmakingRevision: 1, version: 1 }; snapshot.sessions.push(session); snapshot.feeConfigs.push({ id: id(), sessionId: session.id, mode: snapshot.settings?.defaultFeeMode ?? "FIXED_PER_PLAYER", currencyCode: snapshot.settings?.currencyCode ?? "PHP", fixedAmountPerPlayerMinor: snapshot.settings?.defaultFixedFeeMinor ?? null, expectedSessionCostMinor: 0, participationRule: "EVER_CHECKED_IN", frozenAt: null, version: 1 }); return toSessionSummary(snapshot, session); }); }
async function updateFeeConfig(accountId: string, sessionId: string, body: Record<string, unknown>) { return mutate(accountId, sessionId, "FEE_CONFIG_UPDATED", (snapshot) => { requireSnapshot(snapshot, sessionId); const mode = body.mode === "EQUAL_SPLIT" || body.mode === "FIXED_PER_PLAYER" ? body.mode : null; if (!mode) throw new Error("Choose a valid fee mode."); const fixedAmount = body.fixedAmountPerPlayerMinor === null || body.fixedAmountPerPlayerMinor === undefined ? null : Number(body.fixedAmountPerPlayerMinor); const expectedTotal = body.expectedSessionCostMinor === null || body.expectedSessionCostMinor === undefined ? null : Number(body.expectedSessionCostMinor); if ((mode === "FIXED_PER_PLAYER" && (!Number.isInteger(fixedAmount) || (fixedAmount as number) < 0)) || (mode === "EQUAL_SPLIT" && (!Number.isInteger(expectedTotal) || (expectedTotal as number) < 0))) throw new Error("Enter a valid non-negative fee amount."); const fixedValue = fixedAmount ?? 0; const expectedValue = expectedTotal ?? 0; const current = snapshot.feeConfigs.find((item) => item.sessionId === sessionId); const config = { id: current?.id ?? id(), sessionId, mode, currencyCode: current?.currencyCode ?? "PHP", fixedAmountPerPlayerMinor: mode === "FIXED_PER_PLAYER" ? fixedValue : null, expectedSessionCostMinor: mode === "EQUAL_SPLIT" ? expectedValue : null, participationRule: current?.participationRule ?? "EVER_CHECKED_IN", frozenAt: current?.frozenAt ?? null, version: (current?.version ?? 0) + 1 }; snapshot.feeConfigs = [...snapshot.feeConfigs.filter((item) => item.sessionId !== sessionId), config]; const players = snapshot.sessionPlayers.filter((item) => item.sessionId === sessionId && item.checkedInAt); const allocations = mode === "FIXED_PER_PLAYER" ? new Map(players.map((player) => [player.id, fixedValue])) : allocateEqualSplit(expectedValue, players.map((player) => player.id)); for (const player of players) { player.amountDueMinor = allocations.get(player.id) ?? 0; player.version += 1; } return { config, summary: feeSummary(snapshot, sessionId) }; }); }
async function createPayment(accountId: string, sessionId: string, body: Record<string, unknown>) { return mutate(accountId, sessionId, "PAYMENT_RECORDED", (snapshot) => { requireSnapshot(snapshot, sessionId); const sessionPlayerId = String(body.sessionPlayerId ?? ""); const player = snapshot.sessionPlayers.find((item) => item.id === sessionPlayerId && item.sessionId === sessionId); if (!player) throw new Error("Session player not found."); const kind = body.kind === "COLLECTION" || body.kind === "WAIVER" ? body.kind : null; const amountMinor = Number(body.amountMinor); if (!kind || !Number.isInteger(amountMinor) || amountMinor <= 0) throw new Error("Enter a valid payment."); const method = body.method === "CASH" || body.method === "EWALLET" || body.method === "OTHER" ? body.method : undefined; if (kind === "COLLECTION" && !method) throw new Error("A payment method is required for a collection."); const payment: DomainPayment = { id: id(), sessionId, sessionPlayerId, kind, method: method ?? null, amountMinor, reference: typeof body.reference === "string" ? body.reference.trim() || null : null, note: typeof body.note === "string" ? body.note.trim() || null : null, reversalOfPaymentId: null, recordedById: accountId, occurredAt: now(), createdAt: now() }; snapshot.payments.push(payment); return { payment: toPayment(payment), summary: feeSummary(snapshot, sessionId), replayed: false }; }); }
function listSessionPlayers(snapshot: CloudSnapshotV1, sessionId: string) { return snapshot.sessionPlayers.filter((player) => player.sessionId === sessionId).map(toSessionPlayer); }
async function addPlayers(accountId: string, sessionId: string, body: Record<string, unknown>) { return mutate(accountId, sessionId, "PLAYERS_ADDED", (snapshot) => { const session = requireSnapshot(snapshot, sessionId)!; if (["ENDED", "CANCELLED"].includes(session.status)) throw new Error("The session cannot accept players."); const ids = [...new Set((body.playerIds as string[] ?? []).map(String))]; const result: DomainSessionPlayer[] = []; for (const playerId of ids) { const player = snapshot.players.find((item) => item.id === playerId && item.status === "ACTIVE"); if (!player || snapshot.sessionPlayers.some((item) => item.sessionId === sessionId && item.playerId === playerId)) throw new Error("Every selected player must be active and not already in this session."); const created: DomainSessionPlayer & { sessionId: string } = { id: id(), sessionId, playerId, displayName: player.displayName, gender: player.gender, skillLevel: player.skillLevel, skillWeight: player.skillWeight, status: "INACTIVE", matchesPlayed: 0, wins: 0, losses: 0, pointsFor: 0, pointsAgainst: 0, queueEnteredAt: null, lastMatchEndedAt: null, currentMatchId: null, version: 1 }; snapshot.sessionPlayers.push(created); result.push(created); } return result.map(toSessionPlayer); }); }

async function transitionPlayer(accountId: string, sessionId: string, playerId: string, action: string) { return mutate(accountId, sessionId, action.toUpperCase(), (snapshot) => { const player = findPlayer(snapshot, playerId); if (!player) throw new Error("Session player not found."); const timestamp = now(); if (action === "check-in") { if (!["INACTIVE", "CHECKED_OUT"].includes(player.status)) throw new Error("The player cannot be checked in from the current state."); player.status = "WAITING"; player.checkedInAt = player.checkedInAt ?? timestamp; player.checkedOutAt = null; player.queueEnteredAt = timestamp; } else if (action === "rest") { if (player.status !== "WAITING") throw new Error("Only waiting players can rest."); player.status = "RESTING"; player.restStartedAt = timestamp; } else if (action === "resume") { if (player.status !== "RESTING") throw new Error("Only resting players can resume."); player.status = "WAITING"; player.restStartedAt = null; player.queueEnteredAt = timestamp; } else if (action === "check-out") { if (!["INACTIVE", "WAITING", "RESTING"].includes(player.status)) throw new Error("Busy players cannot be checked out."); player.status = "CHECKED_OUT"; player.checkedOutAt = timestamp; player.queueEnteredAt = null; } player.version += 1; return toSessionPlayer(player); }); }
function getQueue(snapshot: CloudSnapshotV1, sessionId: string): QueueState { const players = snapshot.sessionPlayers.filter((player) => player.sessionId === sessionId).map(toSessionPlayer); return { serverTime: now(), inactive: players.filter((player) => ["INACTIVE", "CHECKED_OUT"].includes(player.status)), waiting: players.filter((player) => player.status === "WAITING"), queued: players.filter((player) => player.status === "QUEUED"), playing: players.filter((player) => player.status === "PLAYING"), resting: players.filter((player) => player.status === "RESTING") }; }
async function createCourt(accountId: string, sessionId: string, body: Record<string, unknown>) { return mutate(accountId, sessionId, "COURT_CREATED", (snapshot) => { requireSnapshot(snapshot, sessionId); const name = String(body.name ?? "").trim(); if (!name) throw new Error("Court name is required."); const court = { id: id(), sessionId, name, normalizedName: name.toLowerCase(), displayOrder: snapshot.courts.filter((item) => item.sessionId === sessionId).length, status: "AVAILABLE" as const, currentMatchId: null, closedAt: null, version: 1 }; snapshot.courts.push(court); return toCourt(court); }); }
async function updateCourt(accountId: string, sessionId: string, courtId: string, body: Record<string, unknown>) { return mutate(accountId, sessionId, "COURT_UPDATED", (snapshot) => { const court = findCourt(snapshot, courtId); if (!court || court.sessionId !== sessionId) throw new Error("Court not found."); if (body.name) { court.name = String(body.name).trim(); court.normalizedName = court.name.toLowerCase(); } if (body.status) { if (court.status === "OCCUPIED") throw new Error("Occupied courts cannot be changed."); court.status = body.status as any; court.closedAt = court.status === "CLOSED" ? now() : null; } court.version += 1; return toCourt(court); }); }

function getSuggestion(snapshot: CloudSnapshotV1, sessionId: string, body: Record<string, unknown>) { const session = requireSnapshot(snapshot, sessionId)!; if (session.status !== "ACTIVE") throw new Error("Suggestions require an active session."); const waiting = snapshot.sessionPlayers.filter((item) => item.sessionId === sessionId); const input: MatchPlayer[] = waiting.map((player) => ({ id: player.id, displayName: player.displayName, gender: player.gender, skillWeight: player.skillWeight, skillLevel: player.skillLevel, status: player.status, gamesPlayed: player.matchesPlayed, queueEnteredAt: player.queueEnteredAt ?? null, lastMatchEndedAt: player.lastMatchEndedAt ?? null, manualPriority: player.manualPriority ?? 0 })); const suggestion = suggestMatch(input, String(body.mode) as any, historyMaps(snapshot, sessionId), (body.excludeKeys as string[] | undefined) ?? []); if (!suggestion) return { suggestion: null, cycleRestarted: false, noMatch: { code: "NO_VALID_GROUP", message: "No eligible group satisfies this mode." } }; const expiresAt = Date.now() + 300_000; const convert = (player: MatchPlayer) => ({ ...toSessionPlayer(findPlayer(snapshot, player.id)!), gamesPlayed: player.gamesPlayed }); const value: Suggestion = { token: `local:${id()}`, expiresAt, key: suggestion.key, difference: suggestion.difference, teamATotal: suggestion.teamATotal, teamBTotal: suggestion.teamBTotal, teamA: suggestion.teamA.map(convert), teamB: suggestion.teamB.map(convert), explanation: suggestion.explanation as Suggestion["explanation"] }; return { suggestion: value, cycleRestarted: false }; }

async function createMatch(accountId: string, sessionId: string, body: Record<string, unknown>) { return mutate(accountId, sessionId, "MATCH_CREATED", (snapshot) => { const session = requireSnapshot(snapshot, sessionId)!; if (session.status !== "ACTIVE") throw new Error("Matches require an active session."); const teamA = (body.teamA as string[] ?? []).map(String); const teamB = (body.teamB as string[] ?? []).map(String); if (![1, 2].includes(teamA.length) || teamA.length !== teamB.length || new Set([...teamA, ...teamB]).size !== teamA.length + teamB.length) throw new Error("Choose one player per team for singles or two per team for doubles."); const participants = ensureWaiting(snapshot, sessionId, [...teamA, ...teamB]); const court = body.courtId ? findCourt(snapshot, String(body.courtId)) : undefined; if (body.courtId && (!court || court.sessionId !== sessionId || court.status !== "AVAILABLE" || court.currentMatchId)) throw new Error("The selected court is not available."); const match: DomainMatch = { id: id(), sessionId, courtId: court?.id ?? null, status: court ? "IN_PROGRESS" : "QUEUED", source: body.suggestionToken ? "AUTOMATIC" : "MANUAL", matchmakingMode: null, algorithmVersion: body.suggestionToken ? "v2-rotation" : null, suggestionKey: typeof body.suggestionToken === "string" ? String(body.suggestionToken) : null, suggestionExplanation: null, queuedAt: now(), startedAt: court ? now() : null, completedAt: null, cancelledAt: null, cancellationReason: null, winnerTeam: null, currentRevisionId: null, version: 1, participants: [...teamA.map((playerId, index) => ({ id: id(), matchId: "", sessionPlayerId: playerId, team: "A" as const, teamSlot: index + 1, priorQueueEnteredAt: findPlayer(snapshot, playerId)?.queueEnteredAt ?? null })), ...teamB.map((playerId, index) => ({ id: id(), matchId: "", sessionPlayerId: playerId, team: "B" as const, teamSlot: index + 1, priorQueueEnteredAt: findPlayer(snapshot, playerId)?.queueEnteredAt ?? null }))], scoreRevisions: [] }; match.participants.forEach((participant) => { participant.matchId = match.id; const player = findPlayer(snapshot, participant.sessionPlayerId)!; player.status = court ? "PLAYING" : "QUEUED"; player.currentMatchId = match.id; player.queueEnteredAt = null; player.version += 1; }); if (court) { court.status = "OCCUPIED"; court.currentMatchId = match.id; court.version += 1; } snapshot.matches.push(match); session.matchmakingRevision += 1; session.version += 1; return toMatch(snapshot, match); }); }
async function startSession(accountId: string, sessionId: string) { return mutate(accountId, sessionId, "SESSION_STARTED", (snapshot) => { const session = requireSnapshot(snapshot, sessionId)!; if (!snapshot.courts.some((court) => court.sessionId === sessionId && court.status !== "CLOSED")) throw new Error("Add at least one court before starting."); session.status = "ACTIVE"; session.startedAt = now(); session.version += 1; return toSessionSummary(snapshot, session); }); }
async function startMatch(accountId: string, matchId: string, courtId: string) { return mutate(accountId, "", "MATCH_STARTED", (snapshot) => { const match = snapshot.matches.find((item) => item.id === matchId); const court = findCourt(snapshot, courtId); if (!match || match.status !== "QUEUED" || !court || court.status !== "AVAILABLE" || court.currentMatchId) throw new Error("The selected court is not available."); match.status = "IN_PROGRESS"; match.courtId = court.id; match.startedAt = now(); court.status = "OCCUPIED"; court.currentMatchId = match.id; for (const participant of match.participants) { const player = findPlayer(snapshot, participant.sessionPlayerId); if (player) player.status = "PLAYING"; } return toMatch(snapshot, match); }); }
async function completeMatch(accountId: string, matchId: string, games: Array<{ teamAScore: number; teamBScore: number }>) { return mutate(accountId, "", "MATCH_COMPLETED", (snapshot) => { const match = snapshot.matches.find((item) => item.id === matchId); const session = match && snapshot.sessions.find((item) => item.id === match.sessionId); if (!match || !session || match.status !== "IN_PROGRESS") throw new Error("Only playing matches can be completed."); const validated = validateScores(games, sessionSettings(session)); let aWins = 0; let bWins = 0; for (const game of validated) game.winnerTeam === "A" ? aWins++ : bWins++; const winnerTeam: "A" | "B" = aWins > bWins ? "A" : "B"; const revisionId = id(); const revision = { id: revisionId, matchId, revisionNumber: 1, winnerTeam, reason: null, supersedesRevisionId: null, createdAt: now(), games: validated.map((game, index) => ({ id: id(), scoreRevisionId: revisionId, gameNumber: index + 1, teamAScore: game.teamAScore, teamBScore: game.teamBScore, winnerTeam: game.winnerTeam })) }; match.status = "COMPLETED"; match.completedAt = now(); match.winnerTeam = winnerTeam; match.currentRevisionId = revisionId; match.scoreRevisions.push(revision); const court = findCourt(snapshot, match.courtId ?? undefined); if (court?.currentMatchId === match.id) { court.currentMatchId = null; court.status = court.status === "CLOSED" ? "CLOSED" : "AVAILABLE"; court.version += 1; } for (const participant of match.participants) { const player = findPlayer(snapshot, participant.sessionPlayerId); if (!player) continue; const pointsFor = validated.reduce((sum, game) => sum + (participant.team === "A" ? game.teamAScore : game.teamBScore), 0); const pointsAgainst = validated.reduce((sum, game) => sum + (participant.team === "A" ? game.teamBScore : game.teamAScore), 0); player.status = "WAITING"; player.currentMatchId = null; player.queueEnteredAt = now(); player.matchesPlayed += 1; player.wins += Number(participant.team === winnerTeam); player.losses += Number(participant.team !== winnerTeam); player.pointsFor += pointsFor; player.pointsAgainst += pointsAgainst; player.lastMatchEndedAt = match.completedAt; player.version += 1; } return toMatch(snapshot, match); }); }
async function cancelMatch(accountId: string, matchId: string) { return mutate(accountId, "", "MATCH_DISCARDED", (snapshot) => { const index = snapshot.matches.findIndex((item) => item.id === matchId); if (index < 0) throw new Error("Match not found."); const match = snapshot.matches[index]!; if (!["QUEUED", "IN_PROGRESS"].includes(match.status)) throw new Error("Only queued or playing matches can be discarded."); const court = findCourt(snapshot, match.courtId ?? undefined); if (court?.currentMatchId === match.id) { court.currentMatchId = null; court.status = court.status === "CLOSED" ? "CLOSED" : "AVAILABLE"; } for (const participant of match.participants) { const player = findPlayer(snapshot, participant.sessionPlayerId); if (player) { player.status = "WAITING"; player.currentMatchId = null; player.queueEnteredAt = participant.priorQueueEnteredAt ?? now(); } } snapshot.matches.splice(index, 1); return toMatch(snapshot, match); }); }
async function resetSession(accountId: string, sessionId: string) { return mutate(accountId, sessionId, "SESSION_RESET", (snapshot) => { const session = requireSnapshot(snapshot, sessionId)!; const matchIds = new Set(snapshot.matches.filter((match) => match.sessionId === sessionId).map((match) => match.id)); snapshot.matches = snapshot.matches.filter((match) => match.sessionId !== sessionId); snapshot.payments = snapshot.payments.filter((payment) => payment.sessionId !== sessionId); for (const player of snapshot.sessionPlayers.filter((item) => item.sessionId === sessionId)) { player.status = "INACTIVE"; player.matchesPlayed = 0; player.wins = 0; player.losses = 0; player.pointsFor = 0; player.pointsAgainst = 0; player.currentMatchId = null; player.queueEnteredAt = null; } for (const court of snapshot.courts.filter((item) => item.sessionId === sessionId)) { court.currentMatchId = null; if (court.status !== "CLOSED") court.status = "AVAILABLE"; } session.status = "DRAFT"; session.startedAt = null; session.endedAt = null; session.cancelledAt = null; session.matchmakingRevision += 1; session.version += 1; void matchIds; return toSessionSummary(snapshot, session); }); }
async function deletePlayers(accountId: string, playerIds: string[]) {
  if (!playerIds.length || playerIds.length > 100 || new Set(playerIds).size !== playerIds.length) throw new Error("Select between one and 100 unique players.");
  return mutate(accountId, "", "PLAYERS_DELETED", (snapshot) => {
    const result = applyPlayerDeletion(snapshot, playerIds);
    Object.assign(snapshot, result.snapshot);
    return { deletedPlayerIds: result.impact.playerIds, affectedSessionIds: result.impact.affectedSessionIds, affectedMatchCount: result.impact.affectedMatchIds.length, affectedPaymentCount: result.impact.affectedPaymentIds.length, otherParticipantPlayerIds: result.impact.otherParticipantPlayerIds };
  });
}
async function deleteSession(accountId: string, sessionId: string, disposition: "KEEP" | "DELETE_ALL" = "KEEP") { await mutate(accountId, sessionId, "SESSION_DELETED", (snapshot) => { requireSnapshot(snapshot, sessionId); const rosterPlayerIds = snapshot.sessionPlayers.filter((player) => player.sessionId === sessionId).map((player) => player.playerId); if (disposition === "DELETE_ALL" && rosterPlayerIds.length) { const result = applyPlayerDeletion(snapshot, rosterPlayerIds); Object.assign(snapshot, result.snapshot); } snapshot.sessions = snapshot.sessions.filter((session) => session.id !== sessionId); const sessionPlayers = new Set(snapshot.sessionPlayers.filter((player) => player.sessionId === sessionId).map((player) => player.id)); snapshot.sessionPlayers = snapshot.sessionPlayers.filter((player) => player.sessionId !== sessionId); snapshot.courts = snapshot.courts.filter((court) => court.sessionId !== sessionId); snapshot.matches = snapshot.matches.filter((match) => match.sessionId !== sessionId); snapshot.feeConfigs = snapshot.feeConfigs.filter((fee) => fee.sessionId !== sessionId); snapshot.payments = snapshot.payments.filter((payment) => payment.sessionId !== sessionId && !sessionPlayers.has(payment.sessionPlayerId)); rebuildSnapshotCareerStats(snapshot); }); if (disposition === "DELETE_ALL") await appendAudit(accountId, { sessionId: null, action: "PLAYERS_DELETED", entityType: "ACCOUNT", entityId: accountId, reason: "Session deletion removed rostered player profiles" }); }
function getHistory(snapshot: CloudSnapshotV1, sessionId: string, path: string): HistoryResponse { const page = Number(query(path).get("page") ?? 1); const pageSize = Number(query(path).get("pageSize") ?? 15); const search = query(path).get("search") ?? ""; const result = paginate(historyFor(snapshot, sessionId, search).map((match) => toHistoryMatch(snapshot, match)), page, pageSize); return result; }
function getPlayerHistory(snapshot: CloudSnapshotV1, sessionId: string, sessionPlayerId: string, path: string): PlayerHistoryResponse { const player = findPlayer(snapshot, sessionPlayerId); if (!player || player.sessionId !== sessionId) throw new Error("Session player not found."); const matches = historyFor(snapshot, sessionId).filter((match) => match.participants.some((participant) => participant.sessionPlayerId === sessionPlayerId)); const rows = matches.map((match) => toHistoryMatch(snapshot, match)); let pointsFor = 0; let pointsAgainst = 0; let wins = 0; const partners = new Map<string, number>(); const opponents = new Map<string, number>(); for (const match of matches) { const participant = match.participants.find((item) => item.sessionPlayerId === sessionPlayerId)!; const revision = scoreFor(match); if (revision) { const a = revision.games.reduce((sum, game) => sum + game.teamAScore, 0); const b = revision.games.reduce((sum, game) => sum + game.teamBScore, 0); pointsFor += participant.team === "A" ? a : b; pointsAgainst += participant.team === "A" ? b : a; if (match.winnerTeam === participant.team) wins += 1; } for (const other of match.participants.filter((item) => item.sessionPlayerId !== sessionPlayerId)) { const map = other.team === participant.team ? partners : opponents; map.set(other.sessionPlayerId, (map.get(other.sessionPlayerId) ?? 0) + 1); } } const frequent = (map: Map<string, number>) => [...map.entries()].map(([idValue, count]) => ({ count, displayName: findPlayer(snapshot, idValue)?.displayName ?? "Unknown", sessionPlayerId: idValue })).sort((a, b) => b.count - a.count || a.displayName.localeCompare(b.displayName))[0] ?? null; const paged = paginate(rows, Number(query(path).get("page") ?? 1), Number(query(path).get("pageSize") ?? 15)); return { player: { sessionPlayerId, playerId: player.playerId, displayName: player.displayName, gender: player.gender, skillLevel: player.skillLevel }, stats: { matchesPlayed: matches.length, wins, losses: matches.length - wins, winRateBasisPoints: matches.length ? Math.floor((wins * 10000) / matches.length) : 0, pointsFor, pointsAgainst, pointDifferential: pointsFor - pointsAgainst, averageDurationSeconds: matches.length ? Math.round(matches.map((match) => historyDurationSeconds(match.startedAt, match.completedAt)).filter((value): value is number => value !== null).reduce((sum, value) => sum + value, 0) / Math.max(1, matches.filter((match) => match.startedAt && match.completedAt).length)) : null, mostPlayedPartner: frequent(partners), mostPlayedOpponent: frequent(opponents) }, items: paged.items, pagination: paged.pagination }; }
function getRankings(snapshot: CloudSnapshotV1, sessionId: string): Ranking[] { return snapshot.sessionPlayers.filter((player) => player.sessionId === sessionId).sort((a, b) => b.wins - a.wins || b.matchesPlayed - a.matchesPlayed || a.displayName.localeCompare(b.displayName)).map((player, index) => ({ rank: index + 1, sessionPlayerId: player.id, player: player.displayName, playerId: player.playerId, gender: player.gender, skillLevel: player.skillLevel, matchesPlayed: player.matchesPlayed, wins: player.wins, losses: player.losses, winRateBasisPoints: player.matchesPlayed ? Math.floor((player.wins * 10000) / player.matchesPlayed) : 0, pointsFor: player.pointsFor, pointsAgainst: player.pointsAgainst, pointDifferential: player.pointsFor - player.pointsAgainst })); }

export async function syncAccount(accountId: string, force = false) {
  const local = await getMeta(accountId);
  const status = await request<{ cloudRevision: number }>("/sync/status");
  if (!local || !(await hasSnapshot(accountId))) { const remote = await request<{ snapshot: CloudSnapshotV1; cloudRevision: number }>("/sync/snapshot"); await replaceSnapshot(accountId, remote.snapshot, remote.cloudRevision); try { await navigator.storage?.persist?.(); } catch { /* storage persistence is best effort */ } return { state: "downloaded" as const, cloudRevision: remote.cloudRevision }; }
  if (force) { const remote = await request<{ snapshot: CloudSnapshotV1; cloudRevision: number }>("/sync/snapshot"); await replaceSnapshot(accountId, remote.snapshot, remote.cloudRevision); return { state: "downloaded" as const, cloudRevision: remote.cloudRevision }; }
  if (!local.dirty) { if (status.cloudRevision > local.baseCloudRevision) { const remote = await request<{ snapshot: CloudSnapshotV1; cloudRevision: number }>("/sync/snapshot"); await replaceSnapshot(accountId, remote.snapshot, remote.cloudRevision); return { state: "downloaded" as const, cloudRevision: remote.cloudRevision }; } return { state: "clean" as const, cloudRevision: status.cloudRevision }; }
  if (local.baseCloudRevision !== status.cloudRevision) return { state: "conflict" as const, cloudRevision: status.cloudRevision };
  const operationId = local.pendingOperationId ?? id(); const snapshot = await readSnapshot(accountId); if (!snapshot) throw new Error("Local data is missing."); const events = await listPendingAudits(accountId); const uploaded = await request<{ cloudRevision: number }>("/sync/snapshot", { method: "PUT", body: JSON.stringify({ schemaVersion: 1, deviceId: local.deviceId, operationId, baseCloudRevision: local.baseCloudRevision, force: false, snapshot, auditEvents: events }) }); await replaceSnapshot(accountId, snapshot, uploaded.cloudRevision); return { state: "uploaded" as const, cloudRevision: uploaded.cloudRevision };
}

export async function downloadFromCloud(accountId: string, discard = false) { const meta = await getMeta(accountId); if (meta?.dirty && !discard) throw new Error("Pending local changes must be synced or discarded first."); return syncAccount(accountId, true); }
export { clearAccountData, getMeta, hasSnapshot, saveProfile, storageEstimate };
